### ISSUE TITLE
Good idea!

### ISSUE THREAD

**Issue by cooler-SAI** [SerenityCore-Warhammer-Framework/SerenityCore#1]
hey here! good to see someone try use Trinity and Mangos expirience for warhammer online server. so, what's the plan?) Do you have sniffed warhammer data or something ? may be you have RoR base server? we have this one https://github.com/Shmerrick/ProjectWAR

**Comment by MonkEyBraien** [comment]
My plan is to take the PUP RoR-Base Server apart and understand it first.
When the time comes, combine it with the Trinity ... Yes, there are a few
sniff files. And deep down inside I hope RoR starts talking ^^

Am Mo., 26. Okt. 2020 um 23:05 Uhr schrieb Ander <notifications@github.com>:

**Comment by cooler-SAI** [comment]
good plan! very good)

**Comment by wardev1** [comment]
you have RoR  Server code ? also can you make sniffer  as ror blocked old dll inject sniffer with there punk buster then we can sniffpackets for you
